sudo: false
language: php
php: [5.5, 5.6]

# Only build main branches : feature branches will be covered by the PR builder
branches:
  only:
    - /^[0-9\.]+\.x$/

cache:
  directories:
    - $HOME/.composer/cache/files

before_script:
  - composer self-update
  - composer install

script: bin/phpspec run --format pretty
